# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGTES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rssagg
    ports:
      - 5432:5432
    volumes:
       - ./data:/var/lib/postgresql/data
